Repository fracht/reactive-forms, pull requests merged in 2021-07, with the labels that each got.

#102 Create proxy
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/.eslintrc
  packages/core/src/components/Morfix.tsx
  packages/core/src/components/MorfixContext.ts
  packages/core/src/components/MorfixProxyProvider.tsx
  packages/core/src/components/index.ts
  packages/core/src/constants.ts
  packages/core/src/hooks/useArrayControl.ts
  packages/core/src/hooks/useArrayField.ts
  packages/core/src/hooks/useControlHandlers.ts
  packages/core/src/hooks/useFieldError.ts
  packages/core/src/hooks/useFieldTouched.ts
  packages/core/src/hooks/useMorfix.ts
  packages/core/src/hooks/useMorfixControl.ts
  packages/core/src/hooks/useMorfixMeta.ts
  packages/core/src/hooks/useObjectField.ts
  packages/core/src/typings/FieldContext.ts
  packages/core/src/typings/FieldTouched.ts
  packages/core/src/typings/MorfixMeta.ts
  packages/core/src/typings/index.ts
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useMorfixControl.proxy.test.tsx
  packages/core/tests/hooks/useMorfixControl.test.ts
Labels: feature

#103 Morfix plugins
  packages/core/src/components/MorfixPlugins.tsx
  packages/core/src/components/index.ts
  packages/core/src/hooks/useMorfix.ts
  packages/core/src/hooks/usePlugins.ts
  packages/core/src/typings/Plugin.ts
  packages/core/src/typings/PluginArray.ts
  packages/core/src/typings/index.ts
  packages/core/tests/components/MorfixPlugins.test.tsx
Labels: feature

#105 Renamed @morfix -> @reactive-forms
  .github/ISSUE_TEMPLATE/improve-documentation.md
  .github/release-drafter.yml
  README.md
  docs/next.config.js
  docs/pages/api-reference/hooks/useObservableStorage.md
  docs/pages/api-reference/hooks/useSubmitAction.md
  docs/src/components/DocsFooter.tsx
  docs/src/components/Header.tsx
  docs/src/components/layouts/LayoutDocs.tsx
  docs/tools/docgen/templates/component.ejs
  examples/parcel/package.json
  examples/parcel/src/App.tsx
  package-lock.json
  package.json
  packages/core/README.md
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/Form.tsx
  packages/core/src/components/FormContext.ts
  packages/core/src/components/FormPlugins.tsx
  packages/core/src/components/FormProxyProvider.tsx
  packages/core/src/components/Morfix.tsx
  packages/core/src/components/MorfixContext.ts
  packages/core/src/components/index.ts
  packages/core/src/constants.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/useArrayControl.ts
  packages/core/src/hooks/useFieldError.ts
  packages/core/src/hooks/useFieldTouched.ts
  packages/core/src/hooks/useFieldValidator.ts
  packages/core/src/hooks/useFieldValue.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/useFormContext.ts
  packages/core/src/hooks/useFormControl.ts
  packages/core/src/hooks/useFormMeta.ts
  packages/core/src/hooks/useMorfixContext.ts
  packages/core/src/hooks/useMorfixMeta.ts
  packages/core/src/hooks/usePlugins.ts
  packages/core/src/hooks/useSubmitAction.ts
  packages/core/src/index.ts
  packages/core/src/typings/FormHelpers.ts
  packages/core/src/typings/MorfixHelpers.ts
  packages/core/src/typings/Plugin.ts
  packages/core/src/typings/SubmitAction.ts
  packages/core/src/typings/index.ts
  packages/core/src/utils/runYupSchema.ts
  packages/core/src/utils/yupToFormErrors.ts
  packages/core/tests/components/MorfixPlugins.test.tsx
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useMorfix.test.ts
  packages/core/tests/hooks/useMorfixControl.proxy.test.tsx
  packages/core/tests/hooks/useMorfixControl.test.ts
  packages/core/tests/utils/yupToMorfixErrors.test.ts
  packages/dom/README.md
  packages/dom/package-lock.json
  packages/dom/package.json
Labels: breaking changes

#108 Fixed core package bundle
  packages/core/aqu.config.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/FormPlugins.tsx
  packages/core/src/components/FormProxyProvider.tsx
  packages/core/src/components/index.ts
  packages/core/src/hooks/useControlHandlers.ts
  packages/core/src/hooks/useField.ts
  packages/core/src/hooks/useFieldError.ts
  packages/core/src/hooks/useFieldTouched.ts
  packages/core/src/hooks/useFieldValidator.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/index.ts
  packages/core/src/typings/index.ts
  packages/core/src/utils/runYupSchema.ts
Labels: bug

#107 Dom memory optimization
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/useFieldValidator.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/usePluginAssertion.ts
  packages/core/src/index.ts
  packages/core/src/typings/FormHelpers.ts
  packages/core/src/typings/Plugin.ts
  packages/core/src/utils/runYupSchema.ts
  packages/core/src/utils/yupToFormErrors.ts
  packages/core/tests/hooks/usePluginAssertion.test.tsx
  packages/core/tests/utils/runYupSchema.test.ts
  packages/core/tests/utils/yupToMorfixErrors.test.ts
  packages/dom/aqu.config.json
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/index.ts
  packages/dom/src/plugin.ts
  packages/dom/src/renderComponent.ts
  packages/dom/src/useTextField.ts
  packages/dom/tests/useTextField.test.tsx
Labels: feature

#109 "mrfx" prefix renaming
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/constants.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/typings/FieldError.ts
  packages/core/src/typings/FieldTouched.ts
  packages/core/tests/components/FormPlugins.test.tsx
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useForm.test.ts
  packages/core/tests/hooks/useFormControl.proxy.test.tsx
  packages/core/tests/hooks/useFormControl.test.ts
  packages/core/tests/utils/runYupSchema.test.ts
  packages/core/tests/utils/yupToFormErrors.test.ts
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/plugin.ts
  packages/dom/tests/useTextField.test.tsx
Labels: breaking changes, chore

#110 TextField component
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/TextField.tsx
  packages/dom/src/index.ts
  packages/dom/src/renderComponent.ts
  packages/dom/tests/TextField.test.tsx
  packages/dom/tests/configureEnzyme.ts
  packages/dom/tests/useTextField.test.tsx
Labels: feature

#115 Renamed main component to ReactiveForm
  packages/core/src/components/ReactiveForm.tsx
  packages/core/src/hooks/useFormContext.ts
  packages/core/src/index.ts
  packages/dom/tests/TextField.test.tsx
Labels: breaking changes

#116 Fixed build
  packages/core/aqu.config.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/FormPlugins.tsx
  packages/core/src/components/FormProxyProvider.tsx
  packages/core/src/components/ReactiveForm.tsx
  packages/core/src/hooks/useFieldValue.ts
  packages/core/tests/components/FormPlugins.test.tsx
  packages/dom/aqu.config.json
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/TextField.tsx
  packages/dom/src/index.ts
  packages/dom/src/plugin.ts
  packages/dom/src/renderComponent.ts
  packages/dom/src/useTextField.ts
Labels: chore

#117 Create form component
  packages/dom/src/Form.tsx
  packages/dom/src/index.ts
  packages/dom/tests/Form.test.tsx
Labels: feature

#119 Fixed isSubmitting value in submit function
  packages/core/src/hooks/useForm.ts
Labels: bug

#120 Added name property in ArrayFieldProps
  packages/core/src/hooks/useArrayField.ts
Labels: feature

#121 Create field array component
  packages/dom/src/FieldArray.tsx
  packages/dom/src/index.ts
  packages/dom/tests/FieldArray.test.tsx
Labels: feature

#123 Renamed prepublish script
  package.json
  packages/dom/package-lock.json
Labels: chore

#118 Created SubmitButton
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/SubmitButton.tsx
  packages/dom/src/index.ts
  packages/dom/tests/SubmitButton.test.tsx
Labels: feature

#125 Fixed lockfiles
  packages/core/package-lock.json
  packages/dom/package-lock.json
Labels: bug

#124 Create error message
  packages/dom/src/ErrorMessage.tsx
  packages/dom/src/index.ts
  packages/dom/tests/ErrorMessage.test.tsx
Labels: feature

#127 Initialized x package
  package-lock.json
  package.json
  packages/x/.eslintignore
  packages/x/.eslintrc
  packages/x/LICENSE
  packages/x/README.md
  packages/x/aqu.config.json
  packages/x/jest.config.js
  packages/x/package-lock.json
  packages/x/package.json
  packages/x/src/index.ts
  packages/x/src/plugin.ts
  packages/x/tsconfig.json
  packages/x/tsconfig.test.json
Labels: feature

#128 Create field value component
  packages/dom/src/FieldValue.tsx
  packages/dom/src/index.ts
  packages/dom/tests/FieldValue.test.tsx
Labels: feature
