Repository fracht/reactive-forms, pull requests merged in 2021-08, with the labels that each got.

#129 Dom package types fix
  packages/dom/aqu.config.json
Labels: bug

#130 Created field component
  packages/core/src/components/Field.tsx
  packages/core/src/index.ts
Labels: feature

#131 Validator updates
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/hooks/useControlHandlers.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/useValidationRegistry.ts
  packages/core/src/typings/FieldValidator.ts
  packages/core/src/utils/validatorResultToError.ts
  packages/core/tests/hooks/useForm.test.ts
Labels: feature

#133 Created onValidationSuceed and onReset callbacks
  packages/core/src/hooks/useForm.ts
Labels: feature

#134 Created possibility to specifiy initialValues via promise
  packages/core/src/hooks/useForm.ts
  packages/core/src/typings/FormHelpers.ts
  packages/core/src/utils/loadingGuard.ts
  packages/core/src/utils/useThrowError.ts
  packages/core/tests/utils/loadingGuard.test.ts
  packages/core/tests/utils/useThrowError.test.ts
Labels: feature

#135 Created ReactiveFormProvider and consumer
  packages/core/src/components/ReactiveForm.tsx
  packages/core/src/components/ReactiveFormConsumer.tsx
  packages/core/src/components/ReactiveFormProvider.tsx
  packages/core/src/index.ts
  packages/core/tests/components/FormPlugins.test.tsx
  packages/core/tests/components/ReactiveFormProvider.test.tsx
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useArrayField.test.tsx
  packages/core/tests/hooks/useControlHandlers.test.tsx
  packages/core/tests/hooks/useField.test.tsx
  packages/core/tests/hooks/useFormControl.proxy.test.tsx
Labels: feature

#136 Fixed FieldValue component
  packages/dom/src/FieldValue.tsx
  packages/dom/tests/FieldValue.test.tsx
Labels: bug

#137 Created FieldValueArray
  packages/core/src/hooks/useFieldValueArray.ts
  packages/core/src/index.ts
  packages/core/tests/hooks/useFieldValueArray.test.tsx
  packages/dom/package-lock.json
  packages/dom/package.json
  packages/dom/src/FieldValueArray.tsx
  packages/dom/src/index.ts
  packages/dom/tests/Form.test.tsx
  packages/dom/tests/useTextField.test.tsx
Labels: feature

#138 Fixed renderComponent function and FieldValue
  packages/dom/package-lock.json
  packages/dom/src/FieldValue.tsx
  packages/dom/src/renderComponent.ts
  packages/dom/tests/FieldValue.test.tsx
  packages/dom/tests/renderComponent.test.tsx
Labels: bug

#141 ReactiveFormProvider bug fix
  packages/core/src/components/ReactiveForm.tsx
  packages/core/src/components/ReactiveFormProvider.tsx
  packages/core/tests/components/FormPlugins.test.tsx
  packages/core/tests/components/ReactiveFormProvider.test.tsx
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useArrayField.test.tsx
  packages/core/tests/hooks/useControlHandlers.test.tsx
  packages/core/tests/hooks/useField.test.tsx
  packages/core/tests/hooks/useFieldValueArray.test.tsx
  packages/core/tests/hooks/useFormControl.proxy.test.tsx
Labels: bug

#142 flattenObject Bug fix
  packages/core/src/utils/flattenObject.ts
Labels: bug

#143 Loading bug fixes
  packages/core/src/hooks/useForm.ts
  packages/core/src/utils/useRefCallback.ts
Labels: bug

#144 Created is pending in useForm
  packages/core/src/hooks/useForm.ts
Labels: feature

#145 Made all callbacks referenced
  packages/core/src/hooks/useForm.ts
Labels: bug

#146 Deep remove empty errors in validateForm
  packages/core/src/hooks/useForm.ts
  packages/core/tests/hooks/useForm.test.ts
Labels: bug

#147 Fixed bug with difference map
  .vscode/launch.json
  packages/core/src/utils/excludeOverlaps.ts
  packages/core/src/utils/flattenObject.ts
  packages/core/src/utils/getDifferenceMap.ts
  packages/core/src/utils/joinPaths.ts
  packages/core/tests/utils/getDifferenceMap.test.ts
  packages/core/tests/utils/joinPaths.test.ts
Labels: bug

#148 Fixed validateForm
  packages/core/src/hooks/useForm.ts
Labels: bug

#149 hotfix: render component
  packages/dom/src/renderComponent.ts
  packages/dom/tests/renderComponent.test.tsx
Labels: bug

#151 Fixed bug with initial values
  packages/core/src/hooks/useForm.ts
Labels: bug

#152 Infinity loop bug fix in get difference map
  packages/core/src/utils/getDifferenceMap.ts
  packages/core/tests/utils/getDifferenceMap.test.ts
Labels: bug

#155 Fixed isSubmitting value resetting
  packages/core/src/hooks/useForm.ts
Labels: bug

#156 Proxy validators
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/FormProxyProvider.tsx
  packages/core/src/hooks/useFieldValidator.ts
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/useValidationRegistry.ts
Labels: feature

#157 Fixed interceptedRegisterValidator
  packages/core/src/components/FormProxyProvider.tsx
Labels: bug

#158 Put proxy into context
  packages/core/src/components/FormProxyProvider.tsx
Labels: feature

#160 Fixed bug with errors and touched not being array
  packages/core/src/hooks/useArrayControl.ts
Labels: bug

#159 Pass initialValues in onReset callback
  packages/core/src/hooks/useForm.ts
Labels: bug

#161 Fixed submit
  packages/core/src/hooks/useForm.ts
Labels: bug

#162 Merging initialValues and current values on submit
  packages/core/src/hooks/useForm.ts
Labels: bug

#163 Bug fix
  packages/core/src/hooks/useForm.ts
Labels: bug

#164 disablePureFieldsValidation refactoring
  packages/core/src/hooks/useForm.ts
  packages/core/tests/hooks/useForm.test.ts
Labels: breaking changes

#165 Fixed deepRemoveEmpty function
  packages/core/src/utils/deepRemoveEmpty.ts
  packages/core/tests/utils/deepRemoveEmpty.test.ts
Labels: bug

#166 Fixed optimization issue
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/useValidationRegistry.ts
  packages/core/src/utils/setNestedValues.ts
Labels: bug

#169 Extracted enzyme configuration in setupFiles
  packages/dom/jest.config.js
  packages/dom/tests/ErrorMessage.test.tsx
  packages/dom/tests/FieldArray.test.tsx
  packages/dom/tests/FieldValue.test.tsx
  packages/dom/tests/Form.test.tsx
  packages/dom/tests/SubmitButton.test.tsx
  packages/dom/tests/TextField.test.tsx
  packages/dom/tests/configureEnzyme.ts
  packages/dom/tests/enzyme.config.js
  packages/dom/tests/useTextField.test.tsx
Labels: chore

#167 Fixed validate updated fields
  packages/core/src/hooks/useForm.ts
  packages/core/src/hooks/useValidationRegistry.ts
  packages/core/src/utils/overrideMerge.ts
  packages/core/tests/utils/overrideMerge.test.ts
  packages/core/tsconfig.json
Labels: bug

#170 Updated stocked to the latest beta version
  packages/core/package-lock.json
  packages/core/package.json
Labels: chore

#171 Validation registry validateBranch bug fix
  packages/core/src/hooks/useValidationRegistry.ts
Labels: bug

#172 Validation registry bug fix
  packages/core/src/hooks/useValidationRegistry.ts
Labels: bug

#173 Fixed validateUpdatedFields
  packages/core/src/hooks/useForm.ts
Labels: bug

#174 Fixed useControlHandlers
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/hooks/useControlHandlers.ts
Labels: bug
