Repository fracht/reactive-forms, pull requests merged in 2022-11, with the labels that each got.

#228 Configure changeset CI
  .changeset/configure-changeset-action.md
  .github/workflows/coveralls.yml
  .github/workflows/danger.yml
  .github/workflows/main-ci.yml
  .github/workflows/release.yml
  .github/workflows/size.yml
Labels: pipelines

#230 Update changesets publish action
  .changeset/tall-peas-dance.md
  .github/workflows/release.yml
  package.json
Labels: pipelines

#231 Revert "Version Packages"
  .changeset/configure-changeset-action.md
  .changeset/tall-peas-dance.md
  packages/autosave/CHANGELOG.md
  packages/autosave/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dom/CHANGELOG.md
  packages/dom/package.json
  packages/x/CHANGELOG.md
  packages/x/package.json
Labels: chore

#233 Fixed changests workflow
  .github/workflows/release.yml
  package.json
Labels: chore

#234 Revert "Version Packages"
  .changeset/configure-changeset-action.md
  .changeset/tall-peas-dance.md
  packages/autosave/CHANGELOG.md
  packages/autosave/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dom/CHANGELOG.md
  packages/dom/package.json
  packages/x/CHANGELOG.md
  packages/x/package.json
  pnpm-lock.yaml
Labels: chore

#236 Fixed eslint config package
  tools/eslint-config/package.json
Labels: chore

#237 Revert "Version Packages"
  .changeset/configure-changeset-action.md
  .changeset/tall-peas-dance.md
  packages/autosave/CHANGELOG.md
  packages/autosave/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dom/CHANGELOG.md
  packages/dom/package.json
  packages/x/CHANGELOG.md
  packages/x/package.json
  pnpm-lock.yaml
Labels: chore

#239 Fix publish script
  .changeset/tall-peas-dance.md
  package.json
Labels: chore

#240 Revert "Version Packages"
  .changeset/configure-changeset-action.md
  .changeset/tall-peas-dance.md
  packages/autosave/CHANGELOG.md
  packages/autosave/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dom/CHANGELOG.md
  packages/dom/package.json
  packages/x/CHANGELOG.md
  packages/x/package.json
  pnpm-lock.yaml
Labels: chore

#242 Fixed release pipeline
  .github/workflows/release.yml
Labels: chore

#226 Migrated tests from @testing-library/react-hooks to @testing-library/react in core package
  packages/core/package.json
  packages/core/tests/components/FormPlugins.test.tsx
  packages/core/tests/components/ReactiveFormProvider.test.tsx
  packages/core/tests/hooks/useArrayControl.test.tsx
  packages/core/tests/hooks/useArrayField.test.tsx
  packages/core/tests/hooks/useControlHandlers.test.tsx
  packages/core/tests/hooks/useField.test.tsx
  packages/core/tests/hooks/useFieldError.test.tsx
  packages/core/tests/hooks/useFieldTouched.test.tsx
  packages/core/tests/hooks/useFieldValidator.test.tsx
  packages/core/tests/hooks/useFieldValue.test.tsx
  packages/core/tests/hooks/useFieldValueArray.test.tsx
  packages/core/tests/hooks/useForm.test.tsx
  packages/core/tests/hooks/useFormControl.proxy.test.tsx
  packages/core/tests/hooks/useFormControl.test.ts
  packages/core/tests/hooks/usePluginAssertion.test.tsx
  packages/core/tests/hooks/useProxyInterception.test.tsx
  packages/core/tests/hooks/useSubmitAction.test.tsx
  packages/core/tests/utils/useThrowError.test.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: chore

#244 Use tsc as build tool
  .changeset/use-tsc-in-dom-package.md
  .github/workflows/coveralls.yml
  .github/workflows/main-ci.yml
  package.json
  packages/autosave/package.json
  packages/core/package.json
  packages/dom/package.json
  packages/dom/tsconfig.build.json
  packages/dom/tsconfig.json
  packages/x/package.json
  pnpm-lock.yaml
  turbo.json
Labels: bug

#246 Update ci configuration
  .github/workflows/codeql-analysis.yml
  .github/workflows/main-ci.yml
  package.json
  pnpm-lock.yaml
Labels: chore, pipelines

#245 Updated node version in CI
  .github/workflows/changeset.yml
  .github/workflows/danger.yml
  .github/workflows/main-ci.yml
  .github/workflows/release.yml
  .github/workflows/size.yml
  package.json
  pnpm-lock.yaml
Labels: chore, pipelines

#254 Ignore reactive tools in changeset config
  .changeset/config.json
  .changeset/smart-mails-thank.md
Labels: chore

#257 Added TODO
  .github/workflows/release.yml
Labels: chore

#259 Fix source root option in tsconfig
  .changeset/cuddly-fans-itch.md
  packages/dom/tsconfig.build.json
Labels: chore
