Repository fracht/reactive-forms, pull requests merged in 2023-08, with the labels that each got.

#277 Fixed inconsistency between validateBranch and validateAllFields results
  .changeset/sweet-oranges-double.md
  packages/core/src/hooks/useValidationRegistry.ts
  packages/core/tests/hooks/useValidationRegistry.test.tsx
Labels: bug

#279 Configured provenance
  .changeset/olive-snails-nail.md
  .github/workflows/release.yml
  package.json
Labels: chore, pipelines

#283 Updated pnpm to version 8.x.x
  .clean-publish
  .clean-publish.js
  .editorconfig
  .github/workflows/changeset.yml
  .github/workflows/danger.yml
  .github/workflows/format-files.yml
  .github/workflows/main-ci.yml
  .github/workflows/release.yml
  .travis.yml
  package.json
  packages/autosave/package.json
  packages/core/package.json
  packages/dom/package.json
  packages/dom/tsconfig.build.json
  packages/x/package.json
  pnpm-lock.yaml
  turbo.json
Labels: chore, pipelines

#286 Fix repository link
  package.json
  packages/autosave/package.json
  packages/core/package.json
  packages/dom/package.json
  packages/x/package.json
Labels: chore

#287 Create converter field abstraction
  .changeset/four-turkeys-kiss.md
  packages/x/package.json
  packages/x/src/index.ts
  packages/x/src/useConverterField.ts
  packages/x/tests/useConverterField.test.tsx
  packages/x/tsconfig.json
  pnpm-lock.yaml
Labels: feature

#293 Fix `useConverterField` tests
  packages/x/tests/useConverterField.test.tsx
Labels: chore
